[package]
edition = "2018"
name = "neptune-lang"
version = "0.1.0"

[dependencies]
num_enum = "0.5"
parse_int = "0.5.0"
rustc-hash = "1.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
smartstring = "0.2"
unicode-segmentation = "1.8"
