[package]
name = "neptune-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
dirs = "4.0.0"
neptune-lang = { path = "../" }   
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
tokio = { version = "1", features = ["full"] }
