name: Benchmark

on: workflow_dispatch

env:
  CXX: clang-12

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required languages
        run: |
          apt install luajit lua5.3
          cargo install neptune-cli
      - name: Run benchmark
        run: |
          cd bench;python bench.py
      - uses: peter-evans/create-pull-request@v4
